<?php
/**
 * Mavenbird Technologies Private Limited
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://mavenbird.com/Mavenbird-Module-License.txt
 *
 * =================================================================
 *
 * @category   Mavenbird
 * @package    Mavenbird_PredefinedAdminOrderComments
 * @author     Mavenbird Team
 * @copyright  Copyright (c) 2018-2024 Mavenbird Technologies Private Limited ( http://mavenbird.com )
 * @license    http://mavenbird.com/Mavenbird-Module-License.txt
 */
?>
<?php $helper = $block->getPredefineData(); ?>
<div id="order_history_block" class="edit-order-comments">
    <?php if ($block->canAddComment()):?>
        <div class="order-history-block" id="history_form">

            <div class="admin__field">
                <label for="history_status" class="admin__field-label">
                    <?= $escaper->escapeHtml(__('Status')) ?>
                </label>
                <div class="admin__field-control">
                    <select name="history[status]" id="history_status" class="admin__control-select">
                        <?php foreach ($block->getStatuses() as $_code => $_label): ?>
                            <option value="<?= $escaper->escapeHtml($_code) ?>"
                                <?php if ($_code == $block->getOrder()->getStatus()): ?> 
                                    selected="selected"
                                <?php endif; ?>>
                                <?= $escaper->escapeHtml($_label) ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>

            <?php if ($helper->isEnabled()): ?>
                <div class="admin__field">
                    <label for="history_predefined_comment" class="admin__field-label">
                        <?= $escaper->escapeHtml(__('Predefined Admin Comment')) ?>
                    </label>
                    <div class="admin__field-control">
                        <select name="history[predefined_comment]" id="history_predefined_comment" class="admin__control-select">
                            <option value=""><?= $escaper->escapeHtml(__('Please select a comment')) ?></option>
                            <?php foreach ($block->getPredefinedComments() as $_code => $_label): ?>
                                <option value="<?= $escaper->escapeHtml($_code) ?>">
                                    <?= $escaper->escapeHtml($_label) ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>
            <?php endif; ?>

            <div class="admin__field">
                <label for="history_comment" class="admin__field-label">
                    <?= $escaper->escapeHtml(__('Comment')) ?>
                </label>
                <div class="admin__field-control">
                    <textarea name="history[comment]"
                              rows="3"
                              cols="5"
                              id="history_comment"
                              class="admin__control-textarea"></textarea>
                </div>
            </div>

            <div class="admin__field">
                <div class="order-history-comments-options">
                    <div class="admin__field admin__field-option">
                        <?php if ($block->canSendCommentEmail()): ?>
                            <input name="history[is_customer_notified]"
                                   type="checkbox"
                                   id="history_notify"
                                   class="admin__control-checkbox"
                                   value="1" />
                            <label class="admin__field-label" for="history_notify">
                                <?= $escaper->escapeHtml(__('Notify Customer by Email')) ?>
                            </label>
                        <?php endif; ?>
                    </div>

                    <div class="admin__field admin__field-option">
                        <input name="history[is_visible_on_front]"
                               type="checkbox"
                               id="history_visible"
                               class="admin__control-checkbox"
                               value="1" />
                        <label class="admin__field-label" for="history_visible">
                            <?= $escaper->escapeHtml(__('Visible on Storefront')) ?>
                        </label>
                    </div>
                </div>

                <div class="order-history-comments-actions">
                    <?= $block->getChildHtml('submit_button') ?>
                </div>
            </div>
        </div>
    <?php endif;?>

    <ul class="note-list">
    <?php foreach ($block->getOrder()->getStatusHistoryCollection(true) as $_item): ?>
        <li class="note-list-item">
            <span class="note-list-date">
                <?= $escaper->escapeHtml($block->formatDate($_item->getCreatedAt(), \IntlDateFormatter::MEDIUM)) ?>
            </span>
            <span class="note-list-time">
                <?= $escaper->escapeHtml($block->formatTime($_item->getCreatedAt(), \IntlDateFormatter::MEDIUM)) ?>
            </span>
            <span class="note-list-status"><?= $escaper->escapeHtml($_item->getStatusLabel()) ?></span>
            <span class="note-list-customer">
                <?= $escaper->escapeHtml(__('Customer')) ?>
                <?php if ($block->isCustomerNotificationNotApplicable($_item)): ?>
                    <span class="note-list-customer-notapplicable">
                        <?= $escaper->escapeHtml(__('Notification Not Applicable')) ?>
                    </span>
                <?php elseif ($_item->getIsCustomerNotified()): ?>
                    <span class="note-list-customer-notified"><?= $escaper->escapeHtml(__('Notified')) ?></span>
                <?php else: ?>
                    <span class="note-list-customer-not-notified">
                        <?= $escaper->escapeHtml(__('Not Notified')) ?>
                    </span>
                <?php endif; ?>
            </span>
            <?php if ($_item->getComment()): ?>
                <div class="note-list-comment">
                    <?= $escaper->escapeHtml($_item->getComment(), ['b', 'br', 'strong', 'i', 'u', 'a']) ?>
                </div>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
    </ul>
<script>
    require(['prototype'], function(){
        if($('order_status'))$('order_status').update('<?= $escaper->escapeHtml(
            $block->getOrder()->getStatusLabel()
        ) ?>');

        if ($('history_predefined_comment')) {
            $('history_predefined_comment').observe('change', function(){
                if ($('history_predefined_comment').value) {
                    $('history_comment').value = $('history_predefined_comment').value;
                }
            })
        }
    });
 </script>
</div>
